### ISSUE TITLE
got coredump

### ISSUE THREAD

**Issue by millken** [emmericp/MoonGen#139]
````
[root@test MoonGen]# ./build/MoonGen ./examples/quality-of-service-test.lua 0 1
[INFO]  Initializing DPDK. This will take a few seconds...
[INFO]  Found 1 usable devices:
   Device 0: 90:E2:BA:29:77:A8 (82599EB 10-Gigabit SFI/SFP+ Network Connection)
Segmentation fault (core dumped)

(gdb) bt
#0  0x0000000000422274 in get_socket (port=Unhandled dwarf expression opcode 0xf3
) at /home/millken/MoonGen/src/device.c:276
#1  0x00007fb9ca8d8ea4 in ?? ()
   from /home/millken/MoonGen/deps/luajit/usr/local/lib/libluajit-5.1.so.2
#2  0x00007fb9ca919cb8 in ?? ()
   from /home/millken/MoonGen/deps/luajit/usr/local/lib/libluajit-5.1.so.2
#3  0x00007fb9ca92e606 in ?? ()
   from /home/millken/MoonGen/deps/luajit/usr/local/lib/libluajit-5.1.so.2
#4  0x00007fb9ca8d6db3 in ?? ()
   from /home/millken/MoonGen/deps/luajit/usr/local/lib/libluajit-5.1.so.2
#5  0x00007fb9ca8e657d in lua_pcall ()
   from /home/millken/MoonGen/deps/luajit/usr/local/lib/libluajit-5.1.so.2
#6  0x00000000004202ec in main (argc=4, argv=Unhandled dwarf expression opcode 0xf3
) at /home/millken/MoonGen/src/main.c:37
````

**Comment by emmericp** [comment]
The arguments are the two ports to use. You only have port 0 bound to DPDK but try to use 0 and 1.

(There should probably be a proper error though...)
